name: 'Anaconda Github Action'

on: [push, pull_request]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pythonVersion: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        env-file-name: 'environment\mltool.yml'